// Generated by urdf2quick3dexporter.py from '/home/rutledge/dev/qt-robotics/dogzilla-digitwin/dogzilla/urdf/dogzilla.urdf' on 2026-03-24T19:26:43.953593 | License: see LICENSE
import QtQuick

QtObject {
    property real lfHipJointAngle: 0
    property real lfUpperLegJointAngle: 0
    property real lfLowerLegJointAngle: 0
    property real rfHipJointAngle: 0
    property real rfUpperLegJointAngle: 0
    property real rfLowerLegJointAngle: 0
    property real lhHipJointAngle: 0
    property real lhUpperLegJointAngle: 0
    property real lhLowerLegJointAngle: 0
    property real rhHipJointAngle: 0
    property real rhUpperLegJointAngle: 0
    property real rhLowerLegJointAngle: 0
    readonly property list<variant> jointInfos: [
        {
            "axis": [
                -1.0,
                0.0,
                0.0
            ],
            "lower": -180.00000002350313,
            "name": "lfHipJointAngle",
            "type": "revolute",
            "upper": 180.00000002350313
        },
        {
            "axis": [
                0.0,
                1.0,
                0.0
            ],
            "lower": -180.00000002350313,
            "name": "lfUpperLegJointAngle",
            "type": "revolute",
            "upper": 180.00000002350313
        },
        {
            "axis": [
                0.0,
                1.0,
                0.0
            ],
            "lower": -180.00000002350313,
            "name": "lfLowerLegJointAngle",
            "type": "revolute",
            "upper": 180.00000002350313
        },
        {
            "axis": [
                -1.0,
                0.0,
                0.0
            ],
            "lower": -180.00000002350313,
            "name": "rfHipJointAngle",
            "type": "revolute",
            "upper": 180.00000002350313
        },
        {
            "axis": [
                0.0,
                -1.0,
                0.0
            ],
            "lower": -180.00000002350313,
            "name": "rfUpperLegJointAngle",
            "type": "revolute",
            "upper": 180.00000002350313
        },
        {
            "axis": [
                0.0,
                -1.0,
                0.0
            ],
            "lower": -180.00000002350313,
            "name": "rfLowerLegJointAngle",
            "type": "revolute",
            "upper": 180.00000002350313
        },
        {
            "axis": [
                1.0,
                0.0,
                0.0
            ],
            "lower": -180.00000002350313,
            "name": "lhHipJointAngle",
            "type": "revolute",
            "upper": 180.00000002350313
        },
        {
            "axis": [
                0.0,
                1.0,
                0.0
            ],
            "lower": -180.00000002350313,
            "name": "lhUpperLegJointAngle",
            "type": "revolute",
            "upper": 180.00000002350313
        },
        {
            "axis": [
                0.0,
                1.0,
                0.0
            ],
            "lower": -180.00000002350313,
            "name": "lhLowerLegJointAngle",
            "type": "revolute",
            "upper": 180.00000002350313
        },
        {
            "axis": [
                1.0,
                0.0,
                0.0
            ],
            "lower": -180.00000002350313,
            "name": "rhHipJointAngle",
            "type": "revolute",
            "upper": 180.00000002350313
        },
        {
            "axis": [
                0.0,
                -1.0,
                0.0
            ],
            "lower": -180.00000002350313,
            "name": "rhUpperLegJointAngle",
            "type": "revolute",
            "upper": 180.00000002350313
        },
        {
            "axis": [
                0.0,
                -1.0,
                0.0
            ],
            "lower": -180.00000002350313,
            "name": "rhLowerLegJointAngle",
            "type": "revolute",
            "upper": 180.00000002350313
        }
    ]
}