// Generated by urdf2quick3dexporter.py from 'dogzilla/urdf/dogzilla.urdf' on 2026-03-26T20:31:52.093608 | License: see LICENSE
import QtQuick

QtObject {
    property real lfHipJointAngle: 0
    property real lfUpperLegJointAngle: 0
    property real lfLowerLegJointAngle: 0
    property real rfHipJointAngle: 0
    property real rfUpperLegJointAngle: 0
    property real rfLowerLegJointAngle: 0
    property real lhHipJointAngle: 0
    property real lhUpperLegJointAngle: 0
    property real lhLowerLegJointAngle: 0
    property real rhHipJointAngle: 0
    property real rhUpperLegJointAngle: 0
    property real rhLowerLegJointAngle: 0
    readonly property list<variant> jointInfos: [
        {
            "axis": [
                1.0,
                0.0,
                0.0
            ],
            "lower": -30.999999993225227,
            "name": "lfHipJointAngle",
            "type": "revolute",
            "upper": 30.999999993225227
        },
        {
            "axis": [
                0.0,
                1.0,
                0.0
            ],
            "lower": -65.99999998187978,
            "name": "lfUpperLegJointAngle",
            "type": "revolute",
            "upper": 92.99999997967568
        },
        {
            "axis": [
                0.0,
                1.0,
                0.0
            ],
            "lower": -175.00000000056855,
            "name": "lfLowerLegJointAngle",
            "type": "revolute",
            "upper": -57.00000000362294
        },
        {
            "axis": [
                -1.0,
                0.0,
                0.0
            ],
            "lower": -30.999999993225227,
            "name": "rfHipJointAngle",
            "type": "revolute",
            "upper": 30.999999993225227
        },
        {
            "axis": [
                0.0,
                1.0,
                0.0
            ],
            "lower": -65.99999998187978,
            "name": "rfUpperLegJointAngle",
            "type": "revolute",
            "upper": 92.99999997967568
        },
        {
            "axis": [
                0.0,
                1.0,
                0.0
            ],
            "lower": -175.00000000056855,
            "name": "rfLowerLegJointAngle",
            "type": "revolute",
            "upper": -57.00000000362294
        },
        {
            "axis": [
                1.0,
                0.0,
                0.0
            ],
            "lower": -30.999999993225227,
            "name": "lhHipJointAngle",
            "type": "revolute",
            "upper": 30.999999993225227
        },
        {
            "axis": [
                0.0,
                1.0,
                0.0
            ],
            "lower": -65.99999998187978,
            "name": "lhUpperLegJointAngle",
            "type": "revolute",
            "upper": 92.99999997967568
        },
        {
            "axis": [
                0.0,
                1.0,
                0.0
            ],
            "lower": -175.00000000056855,
            "name": "lhLowerLegJointAngle",
            "type": "revolute",
            "upper": -57.00000000362294
        },
        {
            "axis": [
                -1.0,
                0.0,
                0.0
            ],
            "lower": -30.999999993225227,
            "name": "rhHipJointAngle",
            "type": "revolute",
            "upper": 30.999999993225227
        },
        {
            "axis": [
                0.0,
                1.0,
                0.0
            ],
            "lower": -65.99999998187978,
            "name": "rhUpperLegJointAngle",
            "type": "revolute",
            "upper": 92.99999997967568
        },
        {
            "axis": [
                0.0,
                1.0,
                0.0
            ],
            "lower": -175.00000000056855,
            "name": "rhLowerLegJointAngle",
            "type": "revolute",
            "upper": -57.00000000362294
        }
    ]
}