// Generated by urdf2quick3dexporter.py from 'dogzilla/urdf/dogzilla.urdf' on 2026-03-27T11:41:06.198965 | License: see LICENSE

#include "DogzillaControlBase.h"
#include <QVariantMap>
#include <QVariantList>

DogzillaControlBase::DogzillaControlBase(QObject *parent)
    : QObject(parent)
    , m_values(12)
{
    {
        QVariantMap map;
        map.insert(QStringLiteral("name"), QStringLiteral("lfHipJointAngle"));
        map.insert(QStringLiteral("type"), QStringLiteral("revolute"));
        QVariantList axis;
        axis << 1.0 << 0.0 << 0.0;
        map.insert(QStringLiteral("axis"), axis);
        map.insert(QStringLiteral("lower"), -30.999999993225227);
        map.insert(QStringLiteral("upper"), 30.999999993225227);
        m_jointInfos.append(map);
    }
    {
        QVariantMap map;
        map.insert(QStringLiteral("name"), QStringLiteral("lfUpperLegJointAngle"));
        map.insert(QStringLiteral("type"), QStringLiteral("revolute"));
        QVariantList axis;
        axis << 0.0 << 1.0 << 0.0;
        map.insert(QStringLiteral("axis"), axis);
        map.insert(QStringLiteral("lower"), -65.99999998187978);
        map.insert(QStringLiteral("upper"), 92.99999997967568);
        m_jointInfos.append(map);
    }
    {
        QVariantMap map;
        map.insert(QStringLiteral("name"), QStringLiteral("lfLowerLegJointAngle"));
        map.insert(QStringLiteral("type"), QStringLiteral("revolute"));
        QVariantList axis;
        axis << 0.0 << 1.0 << 0.0;
        map.insert(QStringLiteral("axis"), axis);
        map.insert(QStringLiteral("lower"), -175.00000000056855);
        map.insert(QStringLiteral("upper"), -57.00000000362294);
        m_jointInfos.append(map);
    }
    {
        QVariantMap map;
        map.insert(QStringLiteral("name"), QStringLiteral("rfHipJointAngle"));
        map.insert(QStringLiteral("type"), QStringLiteral("revolute"));
        QVariantList axis;
        axis << -1.0 << 0.0 << 0.0;
        map.insert(QStringLiteral("axis"), axis);
        map.insert(QStringLiteral("lower"), -30.999999993225227);
        map.insert(QStringLiteral("upper"), 30.999999993225227);
        m_jointInfos.append(map);
    }
    {
        QVariantMap map;
        map.insert(QStringLiteral("name"), QStringLiteral("rfUpperLegJointAngle"));
        map.insert(QStringLiteral("type"), QStringLiteral("revolute"));
        QVariantList axis;
        axis << 0.0 << 1.0 << 0.0;
        map.insert(QStringLiteral("axis"), axis);
        map.insert(QStringLiteral("lower"), -65.99999998187978);
        map.insert(QStringLiteral("upper"), 92.99999997967568);
        m_jointInfos.append(map);
    }
    {
        QVariantMap map;
        map.insert(QStringLiteral("name"), QStringLiteral("rfLowerLegJointAngle"));
        map.insert(QStringLiteral("type"), QStringLiteral("revolute"));
        QVariantList axis;
        axis << 0.0 << 1.0 << 0.0;
        map.insert(QStringLiteral("axis"), axis);
        map.insert(QStringLiteral("lower"), -175.00000000056855);
        map.insert(QStringLiteral("upper"), -57.00000000362294);
        m_jointInfos.append(map);
    }
    {
        QVariantMap map;
        map.insert(QStringLiteral("name"), QStringLiteral("lhHipJointAngle"));
        map.insert(QStringLiteral("type"), QStringLiteral("revolute"));
        QVariantList axis;
        axis << 1.0 << 0.0 << 0.0;
        map.insert(QStringLiteral("axis"), axis);
        map.insert(QStringLiteral("lower"), -30.999999993225227);
        map.insert(QStringLiteral("upper"), 30.999999993225227);
        m_jointInfos.append(map);
    }
    {
        QVariantMap map;
        map.insert(QStringLiteral("name"), QStringLiteral("lhUpperLegJointAngle"));
        map.insert(QStringLiteral("type"), QStringLiteral("revolute"));
        QVariantList axis;
        axis << 0.0 << 1.0 << 0.0;
        map.insert(QStringLiteral("axis"), axis);
        map.insert(QStringLiteral("lower"), -65.99999998187978);
        map.insert(QStringLiteral("upper"), 92.99999997967568);
        m_jointInfos.append(map);
    }
    {
        QVariantMap map;
        map.insert(QStringLiteral("name"), QStringLiteral("lhLowerLegJointAngle"));
        map.insert(QStringLiteral("type"), QStringLiteral("revolute"));
        QVariantList axis;
        axis << 0.0 << 1.0 << 0.0;
        map.insert(QStringLiteral("axis"), axis);
        map.insert(QStringLiteral("lower"), -175.00000000056855);
        map.insert(QStringLiteral("upper"), -57.00000000362294);
        m_jointInfos.append(map);
    }
    {
        QVariantMap map;
        map.insert(QStringLiteral("name"), QStringLiteral("rhHipJointAngle"));
        map.insert(QStringLiteral("type"), QStringLiteral("revolute"));
        QVariantList axis;
        axis << -1.0 << 0.0 << 0.0;
        map.insert(QStringLiteral("axis"), axis);
        map.insert(QStringLiteral("lower"), -30.999999993225227);
        map.insert(QStringLiteral("upper"), 30.999999993225227);
        m_jointInfos.append(map);
    }
    {
        QVariantMap map;
        map.insert(QStringLiteral("name"), QStringLiteral("rhUpperLegJointAngle"));
        map.insert(QStringLiteral("type"), QStringLiteral("revolute"));
        QVariantList axis;
        axis << 0.0 << 1.0 << 0.0;
        map.insert(QStringLiteral("axis"), axis);
        map.insert(QStringLiteral("lower"), -65.99999998187978);
        map.insert(QStringLiteral("upper"), 92.99999997967568);
        m_jointInfos.append(map);
    }
    {
        QVariantMap map;
        map.insert(QStringLiteral("name"), QStringLiteral("rhLowerLegJointAngle"));
        map.insert(QStringLiteral("type"), QStringLiteral("revolute"));
        QVariantList axis;
        axis << 0.0 << 1.0 << 0.0;
        map.insert(QStringLiteral("axis"), axis);
        map.insert(QStringLiteral("lower"), -175.00000000056855);
        map.insert(QStringLiteral("upper"), -57.00000000362294);
        m_jointInfos.append(map);
    }
}

double DogzillaControlBase::lfHipJointAngle() const
{
    return m_values[0];
}

void DogzillaControlBase::setLfHipJointAngle(double v)
{
    if (qFuzzyCompare(m_values[0], v))
        return;
    m_values[0] = v;
    emit lfHipJointAngleChanged();
}

double DogzillaControlBase::lfUpperLegJointAngle() const
{
    return m_values[1];
}

void DogzillaControlBase::setLfUpperLegJointAngle(double v)
{
    if (qFuzzyCompare(m_values[1], v))
        return;
    m_values[1] = v;
    emit lfUpperLegJointAngleChanged();
}

double DogzillaControlBase::lfLowerLegJointAngle() const
{
    return m_values[2];
}

void DogzillaControlBase::setLfLowerLegJointAngle(double v)
{
    if (qFuzzyCompare(m_values[2], v))
        return;
    m_values[2] = v;
    emit lfLowerLegJointAngleChanged();
}

double DogzillaControlBase::rfHipJointAngle() const
{
    return m_values[3];
}

void DogzillaControlBase::setRfHipJointAngle(double v)
{
    if (qFuzzyCompare(m_values[3], v))
        return;
    m_values[3] = v;
    emit rfHipJointAngleChanged();
}

double DogzillaControlBase::rfUpperLegJointAngle() const
{
    return m_values[4];
}

void DogzillaControlBase::setRfUpperLegJointAngle(double v)
{
    if (qFuzzyCompare(m_values[4], v))
        return;
    m_values[4] = v;
    emit rfUpperLegJointAngleChanged();
}

double DogzillaControlBase::rfLowerLegJointAngle() const
{
    return m_values[5];
}

void DogzillaControlBase::setRfLowerLegJointAngle(double v)
{
    if (qFuzzyCompare(m_values[5], v))
        return;
    m_values[5] = v;
    emit rfLowerLegJointAngleChanged();
}

double DogzillaControlBase::lhHipJointAngle() const
{
    return m_values[6];
}

void DogzillaControlBase::setLhHipJointAngle(double v)
{
    if (qFuzzyCompare(m_values[6], v))
        return;
    m_values[6] = v;
    emit lhHipJointAngleChanged();
}

double DogzillaControlBase::lhUpperLegJointAngle() const
{
    return m_values[7];
}

void DogzillaControlBase::setLhUpperLegJointAngle(double v)
{
    if (qFuzzyCompare(m_values[7], v))
        return;
    m_values[7] = v;
    emit lhUpperLegJointAngleChanged();
}

double DogzillaControlBase::lhLowerLegJointAngle() const
{
    return m_values[8];
}

void DogzillaControlBase::setLhLowerLegJointAngle(double v)
{
    if (qFuzzyCompare(m_values[8], v))
        return;
    m_values[8] = v;
    emit lhLowerLegJointAngleChanged();
}

double DogzillaControlBase::rhHipJointAngle() const
{
    return m_values[9];
}

void DogzillaControlBase::setRhHipJointAngle(double v)
{
    if (qFuzzyCompare(m_values[9], v))
        return;
    m_values[9] = v;
    emit rhHipJointAngleChanged();
}

double DogzillaControlBase::rhUpperLegJointAngle() const
{
    return m_values[10];
}

void DogzillaControlBase::setRhUpperLegJointAngle(double v)
{
    if (qFuzzyCompare(m_values[10], v))
        return;
    m_values[10] = v;
    emit rhUpperLegJointAngleChanged();
}

double DogzillaControlBase::rhLowerLegJointAngle() const
{
    return m_values[11];
}

void DogzillaControlBase::setRhLowerLegJointAngle(double v)
{
    if (qFuzzyCompare(m_values[11], v))
        return;
    m_values[11] = v;
    emit rhLowerLegJointAngleChanged();
}


QVariantList DogzillaControlBase::jointInfos() const
{
    return m_jointInfos;
}