// Generated by urdf2quick3dexporter.py from '/home/rutledge/dev/qt-robotics/dogzilla-digitwin/dogzilla/urdf/dogzilla.urdf' on 2026-03-24T19:26:43.953593 | License: see LICENSE
import QtQuick
import QtQuick.Window
import Dogzilla

Window {
    width: 1280
    height: 720
    visible: true
    title: qsTr("Dogzilla Preview")

    PreviewScene {
        anchors.fill: parent
    }
}
