#!/usr/bin/env python3
"""Regenerate font.h from the X11 misc bitmap fonts.

Run on a machine that has the xorg-fonts-misc / xfonts-base package installed
(the robot doesn't need this; font.h is checked in).

    ./genfont.py > font.h

Both fonts are 8 pixels tall, which is exactly one SSD1306 memory page, so a
glyph column is one byte and text lines land page-aligned.
"""

import sys
from pcf import Pcf

FONTS = [
    # name, path, codepoint range (inclusive)
    ("5x8", "/usr/share/fonts/X11/misc/5x8-ISO8859-1.pcf.gz", 32, 255),
    ("6x8", "/usr/share/fonts/X11/misc/clR6x8.pcf.gz", 32, 126),
]


def cells(pcf, first, last, width):
    """Yield (codepoint, [column bytes]) with bit N of each byte = pixel row N."""
    for cp in range(first, last + 1):
        g = pcf.glyph(cp) or pcf.glyph(ord('?'))
        rows, lsb, advance, ascent, descent = g
        cols = [0] * width
        for y, row in enumerate(rows[:8]):
            for x in range(width):
                if row & (1 << (max(1, advance) - 1 - x)):
                    cols[x] |= 1 << y
        yield cp, cols


def main():
    out = []
    out.append("/* Generated by genfont.py -- do not edit.")
    out.append(" *")
    out.append(" * Glyph cells are 8 pixels tall (one SSD1306 page). Each glyph is FONT_W")
    out.append(" * column bytes, left to right; in a column byte, bit N is pixel row N,")
    out.append(" * bit 0 topmost -- which is exactly the SSD1306 page-memory layout.")
    out.append(" */")
    out.append("#ifndef FONT_H")
    out.append("#define FONT_H")
    out.append("")
    out.append("typedef struct {")
    out.append("    const char *name;")
    out.append("    unsigned char width;          /* cell width in pixels, spacing included */")
    out.append("    unsigned short first, last;    /* codepoint range covered */")
    out.append("    const unsigned char *bits;     /* (last - first + 1) * width bytes */")
    out.append("} OledFont;")
    out.append("")

    tables = []
    for name, path, first, last in FONTS:
        pcf = Pcf(path)
        width = int(pcf.props.get("QUAD_WIDTH") or name.split("x")[0])
        ident = "font_%s_bits" % name
        out.append("/* %s" % pcf.props.get("FONT", path))
        for key in ("COPYRIGHT", "NOTICE"):
            if pcf.props.get(key):
                out.append(" * %s: %s" % (key.title(), pcf.props[key]))
        out.append(" */")
        out.append("static const unsigned char %s[] = {" % ident)
        for cp, cols in cells(pcf, first, last, width):
            label = chr(cp) if 32 < cp < 127 else "."
            if label in ("\\", "*", "/"):
                label = "."
            out.append("    %s /* %3d %s */" % (
                "".join("0x%02x, " % b for b in cols), cp, label))
        out.append("};")
        out.append("")
        tables.append((name, width, first, last, ident))

    out.append("static const OledFont oled_fonts[] = {")
    for name, width, first, last, ident in tables:
        out.append('    { "%s", %d, %d, %d, %s },' % (name, width, first, last, ident))
    out.append("};")
    out.append("#define OLED_FONT_COUNT (sizeof(oled_fonts) / sizeof(oled_fonts[0]))")
    out.append("")
    out.append("#endif /* FONT_H */")
    sys.stdout.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
