// Generated by urdf2quick3dexporter.py from '/home/rutledge/dev/qt-robotics/dogzilla-digitwin/dogzilla/urdf/dogzilla.urdf' on 2026-03-24T19:26:43.953593 | License: see LICENSE
import QtQuick
import QtQuick.Controls
import QtQuick.Layouts
import QtGraphs

ScrollView {
    id: root

    required property var targetRobot
    property alias batteryLevel: batteryIndicator.level
    property var joints: targetRobot && targetRobot.control ? targetRobot.control.jointInfos : []
    clip: true

    // ROS header stamp time in seconds, temperature in °C
    function addTemperatureSample(t, v) {
        telemetryChart.latestTemperature = v
        // keep t small to work around the usual GPU large-number bugs
        t -= telemetryChart.secondsWhenTodayBegan
        temperatureSeries.append(t, v)
        xAxis.max = t
        xAxis.min = t - telemetryChart.depth
        // window slides left as t grows; trim points that slid off:
        while (temperatureSeries.count > 0 && temperatureSeries.at(0).x < xAxis.min)
            temperatureSeries.remove(0)
    }

    // ROS header stamp time in seconds, cpu percentage, fan level
    function addTelemetrySample(t, cpu, fan) {
        // console.log("t", t, "since midnight", t - telemetryChart.secondsWhenTodayBegan,
        //      "cpu", cpu, "fan", fan)
        telemetryChart.latestCpu = cpu
        telemetryChart.latestFan = fan
        // keep t small to work around the usual GPU large-number bugs
        t -= telemetryChart.secondsWhenTodayBegan
        xAxis.max = t
        xAxis.min = t - telemetryChart.depth
        fanSeries.append(t, fan * 20) // make it fit the yAxis range
        while (fanSeries.count > 0 && fanSeries.at(0).x < xAxis.min)
            fanSeries.remove(0)
        cpuSeries.append(t, cpu)
        while (cpuSeries.count > 0 && cpuSeries.at(0).x < xAxis.min)
            cpuSeries.remove(0)
    }


    Connections {
        target: root.targetRobot && root.targetRobot.control ? root.targetRobot.control : null
        ignoreUnknownSignals: true
        function onJointInfosChanged() {
            root.joints = root.targetRobot && root.targetRobot.control ? root.targetRobot.control.jointInfos : [];
        }
    }

    ColumnLayout {
        anchors.fill: parent
        anchors.margins: 6
        spacing: 6

        RowLayout {
            Pane {
                Layout.fillWidth: true
                padding: 8
                height: 24
                RowLayout {
                    anchors.fill: parent
                    BatteryIndicator {
                        id: batteryIndicator
                        level: 0 // until we know
                        Layout.alignment: Qt.AlignRight
                    }
                }
            }
        }

        GraphsView {
            id: telemetryChart
            property int depth: 200
            property real latestTemperature: 20
            property int latestFan: 0
            property int latestCpu: 0

            Layout.fillWidth: true
            height: 60
            marginLeft: 6; marginRight: 50; marginTop: 0; marginBottom: 0
            theme: GraphsTheme {
                colorScheme: GraphsTheme.ColorScheme.Dark
                grid.mainColor: "#111122"
            }

            property real secondsWhenTodayBegan: (new Date().setUTCHours(0,0,0,0)) / 1000

            axisX: ValueAxis {
                id: xAxis
                max: 200
                visible: false
            }
            axisY: ValueAxis {
                id: yAxis
                min: 0
                max: 100
                visible: false // because labels are unreasonable
                // labelsVisble: false // nope: missing API
            }

            LineSeries {
                id: temperatureSeries
                color: "orange"
                joinStyle: Qt.RoundJoin
            }

            LineSeries {
                id: fanSeries
                color: "cyan"
                joinStyle: Qt.RoundJoin
            }

            LineSeries {
                id: cpuSeries
                color: "lightgreen"
                joinStyle: Qt.RoundJoin
            }

            data: Column {
                anchors {
                    right: parent.right
                    rightMargin: 6
                    verticalCenter: parent.verticalCenter
                }
                Text {
                    id: temperatureLabel
                    color: "orange"
                    anchors.right: parent.right
                    horizontalAlignment: Text.AlignRight
                    text: telemetryChart.latestTemperature.toFixed(1) + " °C"
                }
                Text {
                    id: fanLabel
                    color: "cyan"
                    anchors.right: parent.right
                    horizontalAlignment: Text.AlignRight
                    text: "fan " + telemetryChart.latestFan
                }
                Text {
                    id: cpuLabel
                    color: "lightgreen"
                    anchors.right: parent.right
                    horizontalAlignment: Text.AlignRight
                    text: `cpu ${telemetryChart.latestCpu}%`
                }
            }
        }

        Repeater {
            model: root.joints
            delegate: Pane {
                Layout.fillWidth: true
                padding: 8

                required property string name
                required property real lower
                required property real upper
                required property string type

                RowLayout {
                    anchors.fill: parent

                    Text { text: name; width: 40 }
                    Slider {
                        id: s; from: lower; to: upper; Layout.fillWidth: true
                        stepSize: type === "prismatic" ? 0.001 : 0.1

                        onValueChanged: {
                            root.targetRobot.control[name] = value;
                        }
                    }
                    Text { text: Number(s.value).toFixed(1); width: 50; horizontalAlignment: Text.AlignRight }
                }
            }
        }
    }
}
