// Generated by urdf2quick3dexporter.py from '/home/rutledge/dev/qt-robotics/dogzilla-digitwin/dogzilla/urdf/dogzilla.urdf' on 2026-03-24T19:26:43.953593 | License: see LICENSE
import QtQuick
import QtQuick.Controls
import QtQuick.Layouts
import QtGraphs

ScrollView {
    id: root

    required property var targetRobot
    property alias batteryLevel: batteryIndicator.level
    property var joints: targetRobot && targetRobot.control ? targetRobot.control.jointInfos : []
    clip: true

    // time in seconds, v in °C
    function addTemperatureSample(t, v) {
        temperatureChart.addSample(t, v)
    }

    // t in seconds (ROS time, from the message header stamp)
    function addTelemetrySample(t, cpu, fan) {
        console.log("t", t, "cpu", cpu, "fan", fan)
    }

    Connections {
        target: root.targetRobot && root.targetRobot.control ? root.targetRobot.control : null
        ignoreUnknownSignals: true
        function onJointInfosChanged() {
            root.joints = root.targetRobot && root.targetRobot.control ? root.targetRobot.control.jointInfos : [];
        }
    }

    ColumnLayout {
        anchors.fill: parent
        anchors.margins: 6
        spacing: 6

        RowLayout {
            Pane {
                Layout.fillWidth: true
                padding: 8
                height: 24
                RowLayout {
                    anchors.fill: parent
                    BatteryIndicator {
                        id: batteryIndicator
                        level: 0 // until we know
                        Layout.alignment: Qt.AlignRight
                    }
                }
            }
        }

        GraphsView {
            id: temperatureChart
            property int depth: 200
            property real latestSample: 20

            Layout.fillWidth: true
            height: 40
            marginLeft: 6; marginRight: 50; marginTop: 0; marginBottom: 0 // OMG
            theme: GraphsTheme {
                colorScheme: GraphsTheme.ColorScheme.Dark
                grid.mainColor: "#111122"
            }

            function addSample(t, v) {
                latestSample = v
                // keep t small to work around the usual large-number bugs
                const floatRangeFinaglingFactor = 1780000000
                t -= floatRangeFinaglingFactor
                temperatureSeries.append(t, v)
                xAxis.max = t
                xAxis.min = t - temperatureChart.depth
                // window slides left as t grows; trim points that slid off:
                while (temperatureSeries.count > 0 && temperatureSeries.at(0).x < xAxis.min)
                    temperatureSeries.remove(0)
            }

            axisX: ValueAxis {
                id: xAxis
                max: 200
                visible: false
            }
            axisY: ValueAxis {
                id: yAxis
                min: 20
                max: 100
                visible: false // because labels are unreasonable
                // labelsVisble: false // nope: missing API
            }

            LineSeries {
                id: temperatureSeries
                color: "orange"
                joinStyle: Qt.RoundJoin
            }

            data: Text {
                id: temperatureLabel
                anchors.right: parent.right
                anchors.rightMargin: 6
                anchors.verticalCenter: parent.verticalCenter
                color: "orange"
                text: temperatureChart.latestSample.toFixed(1) + " °C"
            }
        }

        Repeater {
            model: root.joints
            delegate: Pane {
                Layout.fillWidth: true
                padding: 8

                required property string name
                required property real lower
                required property real upper
                required property string type

                RowLayout {
                    anchors.fill: parent

                    Text { text: name; width: 40 }
                    Slider {
                        id: s; from: lower; to: upper; Layout.fillWidth: true
                        stepSize: type === "prismatic" ? 0.001 : 0.1

                        onValueChanged: {
                            root.targetRobot.control[name] = value;
                        }
                    }
                    Text { text: Number(s.value).toFixed(1); width: 50; horizontalAlignment: Text.AlignRight }
                }
            }
        }
    }
}
