// Generated by urdf2quick3dexporter.py from '/home/rutledge/dev/qt-robotics/dogzilla-digitwin/dogzilla/urdf/dogzilla.urdf' on 2026-03-24T19:26:43.953593 | License: see LICENSE
import QtQuick
import QtQuick.Controls
import QtQuick.Layouts
import QtGraphs
import Dogzilla

ColumnLayout {
    id: root
    required property var targetRobot
    signal speakText(string text)
    signal stopSpeaking()
    signal sendText(string text)
    property alias batteryLevel: batteryIndicator.level
    property alias motorsEngaged: engageSwitch.checked

    // Robot audio mixer, one row per channel. Each slider owns the *desired*
    // value for its channel (PreviewScene binds it into that channel's
    // SetVolumeServiceClient.request); robotVolume is what the robot last
    // reported on the latched mixer topic. The slider is seeded once from the
    // first latched sample, then the user owns it. `live` gates the client's
    // autoCall: nothing is dispatched until the slider has a real starting
    // point (seeded, or the user deliberately moved it -- their intent wins
    // and is applied when the robot appears), so a freshly started twin can
    // never zero the robot's mixer with its untouched sliders. The first
    // dispatch after seeding just echoes the robot's own value (harmless).
    component VolumeRow : RowLayout {
        id: volumeRow
        property alias label: iconLabel.text
        property real robotVolume: 0
        readonly property real desired: slider.value
        readonly property bool live: slider.seeded || slider.touched
        onRobotVolumeChanged: {
            if (!slider.seeded && !slider.touched) {
                slider.value = robotVolume
                slider.seeded = true
            }
        }
        Label { id: iconLabel }
        Slider {
            id: slider
            property bool seeded: false
            property bool touched: false
            from: 0
            to: 1
            Layout.fillWidth: true
            onMoved: touched = true
        }
        Label {
            // what the robot last reported (may lag the slider while a call
            // is in flight)
            text: `${Math.round(volumeRow.robotVolume * 100)}%`
        }
    }

    property alias robotMasterVolume: masterRow.robotVolume
    readonly property real desiredMasterVolume: masterRow.desired
    readonly property bool masterVolumeLive: masterRow.live
    property alias robotMicVolume: micRow.robotVolume
    readonly property real desiredMicVolume: micRow.desired
    readonly property bool micVolumeLive: micRow.live
    property var joints: targetRobot && targetRobot.control ? targetRobot.control.jointInfos : []
    spacing: 6

    // ROS header stamp time in seconds, temperature in °C
    function addTemperatureSample(t, v) {
        telemetryChart.latestTemperature = v
        // keep t small to work around the usual GPU large-number bugs
        t -= telemetryChart.secondsWhenTodayBegan
        temperatureSeries.append(t, v)
        xAxis.max = t
        xAxis.min = t - telemetryChart.depth
        // window slides left as t grows; trim points that slid off:
        while (temperatureSeries.count > 0 && temperatureSeries.at(0).x < xAxis.min)
            temperatureSeries.remove(0)
    }

    // ROS header stamp time in seconds, cpu percentage, fan level
    function addTelemetrySample(t, cpu, fan) {
        // console.log("t", t, "since midnight", t - telemetryChart.secondsWhenTodayBegan,
        //      "cpu", cpu, "fan", fan)
        telemetryChart.latestCpu = cpu
        telemetryChart.latestFan = fan
        // keep t small to work around the usual GPU large-number bugs
        t -= telemetryChart.secondsWhenTodayBegan
        xAxis.max = t
        xAxis.min = t - telemetryChart.depth
        fanSeries.append(t, fan * 20) // make it fit the yAxis range
        while (fanSeries.count > 0 && fanSeries.at(0).x < xAxis.min)
            fanSeries.remove(0)
        cpuSeries.append(t, cpu)
        while (cpuSeries.count > 0 && cpuSeries.at(0).x < xAxis.min)
            cpuSeries.remove(0)
    }

    function addChatMessage(msg) {
        console.log("chat message", JSON.stringify(msg))
        chatModel.addMessage(msg.text, msg.source)
    }

    Connections {
        target: root.targetRobot && root.targetRobot.control ? root.targetRobot.control : null
        ignoreUnknownSignals: true
        function onJointInfosChanged() {
            root.joints = root.targetRobot && root.targetRobot.control ? root.targetRobot.control.jointInfos : [];
        }
    }

    Rectangle {
        Layout.fillWidth: true
        height: 24
        Layout.preferredHeight: 24
        RowLayout {
            width: parent.width - 8
            anchors.centerIn: parent
            Switch {
                Layout.alignment: Qt.AlignVCenter
                id: engageSwitch
                text: checked ? "Engaged" : "Relaxed"
            }
            BatteryIndicator {
                id: batteryIndicator
                level: 0 // until we know
                Layout.alignment: Qt.AlignRight | Qt.AlignVCenter
            }
        }
    }

    VolumeRow { id: masterRow; label: "🔊"; Layout.fillWidth: true }
    VolumeRow { id: micRow; label: "🎤"; Layout.fillWidth: true }

    GraphsView {
        id: telemetryChart
        property int depth: 200
        property real latestTemperature: 20
        property int latestFan: 0
        property int latestCpu: 0

        Layout.fillWidth: true
        height: 60
        marginLeft: 6; marginRight: 50; marginTop: 0; marginBottom: 0
        theme: GraphsTheme {
            colorScheme: GraphsTheme.ColorScheme.Dark
            grid.mainColor: "#111122"
        }

        property real secondsWhenTodayBegan: (new Date().setUTCHours(0,0,0,0)) / 1000

        axisX: ValueAxis {
            id: xAxis
            max: 200
            visible: false
        }
        axisY: ValueAxis {
            id: yAxis
            min: 0
            max: 100
            visible: false // because labels are unreasonable
            // labelsVisble: false // nope: missing API
        }

        LineSeries {
            id: temperatureSeries
            color: "orange"
            joinStyle: Qt.RoundJoin
        }

        LineSeries {
            id: fanSeries
            color: "cyan"
            joinStyle: Qt.RoundJoin
        }

        LineSeries {
            id: cpuSeries
            color: "lightgreen"
            joinStyle: Qt.RoundJoin
        }

        data: Column {
            anchors {
                right: parent.right
                rightMargin: 6
                verticalCenter: parent.verticalCenter
            }
            Text {
                id: temperatureLabel
                color: "orange"
                anchors.right: parent.right
                horizontalAlignment: Text.AlignRight
                text: telemetryChart.latestTemperature.toFixed(1) + " °C"
            }
            Text {
                id: fanLabel
                color: "cyan"
                anchors.right: parent.right
                horizontalAlignment: Text.AlignRight
                text: "fan " + telemetryChart.latestFan
            }
            Text {
                id: cpuLabel
                color: "lightgreen"
                anchors.right: parent.right
                horizontalAlignment: Text.AlignRight
                text: `cpu ${telemetryChart.latestCpu}%`
            }
        }
    }

    ChatView {
        id: chatView
        Layout.fillWidth: true
        Layout.fillHeight: true
        implicitHeight: 1024
        model: ChatModel {
            id: chatModel
            onSizeChanged: chatView.positionViewAtEnd()
        }
    }

    RowLayout {
        RoundButton {
            text: "⬛"
            Layout.alignment: Qt.AlignVCenter
            onClicked: root.stopSpeaking()
        }
        TextField {
            id: textToSend
            placeholderText: "talk to Dogzilla"
            Layout.alignment: Qt.AlignVCenter
            Layout.fillWidth: true
            onAccepted: root.sendText(textToSend.text)
        }
        RoundButton {
            text: "Speak"
            Layout.alignment: Qt.AlignVCenter
            onClicked: root.speakText(textToSend.text)
        }
        RoundButton {
            text: "Send"
            Layout.alignment: Qt.AlignVCenter
            onClicked: root.sendText(textToSend.text)
        }
    }
}
