// Generated by urdf2quick3dexporter.py from 'dogzilla/urdf/dogzilla.urdf' on 2026-03-27T11:41:06.198965 | License: see LICENSE

#ifndef DOGZILLA_CONTROL_BASE_H
#define DOGZILLA_CONTROL_BASE_H

#include <QObject>
#include <QVector>
#include <QVariantList>

class DogzillaControlBase : public QObject
{
    Q_OBJECT

#define DEFINE_JOINT_PROPERTY(IDX, NAME, NAME_CAP)     Q_PROPERTY(double NAME READ NAME WRITE set##NAME_CAP NOTIFY NAME##Changed)

    DEFINE_JOINT_PROPERTY(0, lfHipJointAngle, LfHipJointAngle)
    DEFINE_JOINT_PROPERTY(1, lfUpperLegJointAngle, LfUpperLegJointAngle)
    DEFINE_JOINT_PROPERTY(2, lfLowerLegJointAngle, LfLowerLegJointAngle)
    DEFINE_JOINT_PROPERTY(3, rfHipJointAngle, RfHipJointAngle)
    DEFINE_JOINT_PROPERTY(4, rfUpperLegJointAngle, RfUpperLegJointAngle)
    DEFINE_JOINT_PROPERTY(5, rfLowerLegJointAngle, RfLowerLegJointAngle)
    DEFINE_JOINT_PROPERTY(6, lhHipJointAngle, LhHipJointAngle)
    DEFINE_JOINT_PROPERTY(7, lhUpperLegJointAngle, LhUpperLegJointAngle)
    DEFINE_JOINT_PROPERTY(8, lhLowerLegJointAngle, LhLowerLegJointAngle)
    DEFINE_JOINT_PROPERTY(9, rhHipJointAngle, RhHipJointAngle)
    DEFINE_JOINT_PROPERTY(10, rhUpperLegJointAngle, RhUpperLegJointAngle)
    DEFINE_JOINT_PROPERTY(11, rhLowerLegJointAngle, RhLowerLegJointAngle)

    Q_PROPERTY(QVariantList jointInfos READ jointInfos CONSTANT)

public:
    explicit DogzillaControlBase(QObject *parent = nullptr);

    QVariantList jointInfos() const;

    double lfHipJointAngle() const;
    void setLfHipJointAngle(double v);
    double lfUpperLegJointAngle() const;
    void setLfUpperLegJointAngle(double v);
    double lfLowerLegJointAngle() const;
    void setLfLowerLegJointAngle(double v);
    double rfHipJointAngle() const;
    void setRfHipJointAngle(double v);
    double rfUpperLegJointAngle() const;
    void setRfUpperLegJointAngle(double v);
    double rfLowerLegJointAngle() const;
    void setRfLowerLegJointAngle(double v);
    double lhHipJointAngle() const;
    void setLhHipJointAngle(double v);
    double lhUpperLegJointAngle() const;
    void setLhUpperLegJointAngle(double v);
    double lhLowerLegJointAngle() const;
    void setLhLowerLegJointAngle(double v);
    double rhHipJointAngle() const;
    void setRhHipJointAngle(double v);
    double rhUpperLegJointAngle() const;
    void setRhUpperLegJointAngle(double v);
    double rhLowerLegJointAngle() const;
    void setRhLowerLegJointAngle(double v);

signals:
    void lfHipJointAngleChanged();
    void lfUpperLegJointAngleChanged();
    void lfLowerLegJointAngleChanged();
    void rfHipJointAngleChanged();
    void rfUpperLegJointAngleChanged();
    void rfLowerLegJointAngleChanged();
    void lhHipJointAngleChanged();
    void lhUpperLegJointAngleChanged();
    void lhLowerLegJointAngleChanged();
    void rhHipJointAngleChanged();
    void rhUpperLegJointAngleChanged();
    void rhLowerLegJointAngleChanged();

private:
    QVector<double> m_values;
    QVariantList m_jointInfos;
};

#endif // DOGZILLA_CONTROL_BASE_H