// Generated by urdf2quick3dexporter.py from '/home/rutledge/dev/qt-robotics/dogzilla-digitwin/dogzilla/urdf/dogzilla.urdf' on 2026-03-24T19:26:43.953593 | License: see LICENSE
import QtQuick
import QtQuick.Controls
import QtQuick3D
import QtQuick3D.Helpers
import QtRos2.SensorMsgs as SensorMsgs
import QtRos2.Core
import Dogzilla

Item {
    id: root
    implicitWidth: 1920
    implicitHeight: 1080

    View3D {
        id: view3D
        anchors.fill: parent

        camera: sceneCamera
        environment: sceneEnvironment

        SceneEnvironment {
            id: sceneEnvironment
            antialiasingMode: SceneEnvironment.MSAA
            antialiasingQuality: SceneEnvironment.High
        }

        Node {
            id: cameraNode
            eulerRotation: Qt.vector3d(-30, 30, 0)
            PerspectiveCamera {
                id: sceneCamera
                z: 1000
            }

            DirectionalLight {
                id: directionalLight
                eulerRotation: Qt.vector3d(-30, 30, 0)
            }
        }

        OrbitCameraController {
            origin: cameraNode
            camera: sceneCamera
        }

        AxisHelper {}

        Dogzilla {
            id: robotRoot
            control: DogzillaControl {
                id: ctl
            }
        }
    }

    Ros2Node {
        id: rosNode
        nodeName: "dogzilla"

        SensorMsgs.JointStateSubscriber {
            id: jointStateSubscriber
            topic: `/${rosNode.nodeName}/joint_states`
            qos.queueSize: 1
            qos.reliability: SensorMsgs.JointStateSubscriber.ReliabilityBestEffort
            qos.history: SensorMsgs.JointStateSubscriber.HistoryKeepLast

            onMessageReceived: function (msg) {
                // console.log("JointStateSubscriber got", msg.name, msg.position, JSON.stringify(msg))
                robotRoot.control.updateJointState(msg.name, msg.position);
            }
        }
    }

    ControlPanel {
        id: panel
        anchors.right: parent.right
        anchors.top: parent.top
        anchors.bottom: parent.bottom
        anchors.margins: 12
        width: Math.min(420, Math.max(280, parent.width * 0.28))
        targetRobot: robotRoot
    }
}
