// Generated by urdf2quick3dexporter.py from '/home/rutledge/dev/qt-robotics/dogzilla-digitwin/dogzilla/urdf/dogzilla.urdf' on 2026-03-24T19:26:43.953593 | License: see LICENSE
import QtQuick
import QtQuick.Controls
import QtQuick3D
import QtQuick3D.Helpers
import QtRos2.Core as Ros2
import QtRos2.GeometryMsgs as GeomMsgs
import QtRos2.SensorMsgs as SensorMsgs
import Dogzilla

Item {
    id: root
    implicitWidth: 1920
    implicitHeight: 1080

    View3D {
        id: view3D
        anchors.fill: parent

        camera: sceneCamera
        environment: sceneEnvironment

        SceneEnvironment {
            id: sceneEnvironment
            clearColor: "#222"
            backgroundMode: SceneEnvironment.Color
            antialiasingMode: SceneEnvironment.MSAA
            antialiasingQuality: SceneEnvironment.High
        }

        Node {
            id: cameraNode
            eulerRotation: Qt.vector3d(-10, 150, 0)
            PerspectiveCamera {
                id: sceneCamera
                z: 1000
                property real stickDistance: 300
                property real halfV: stickDistance * Math.tan(sceneCamera.fieldOfView / 2 * Math.PI / 180)
                property real halfH: halfV * (view3D.width / view3D.height)

                Node {
                    id: rightStick
                    x: ((rightStickControl.x + rightStickControl.width  / 2) / view3D.width  - 0.5) * 2 * sceneCamera.halfH
                    y: (0.5 - (rightStickControl.y + rightStickControl.height / 2) / view3D.height) * 2 * sceneCamera.halfV
                    z: -sceneCamera.stickDistance
                    // Perspective compensation: rotate to face the camera eye at the origin
                    eulerRotation.y: -Math.atan2(x, sceneCamera.stickDistance) * 180 / Math.PI
                    eulerRotation.x: Math.atan2(y, sceneCamera.stickDistance) * 180 / Math.PI
                    ThumbStick {
                        axes: rightStickControl.axes
                    }
                }

                Node {
                    id: leftStick
                    x: ((leftStickControl.x + leftStickControl.width  / 2) / view3D.width  - 0.5) * 2 * sceneCamera.halfH
                    y: (0.5 - (leftStickControl.y + leftStickControl.height / 2) / view3D.height) * 2 * sceneCamera.halfV
                    z: -sceneCamera.stickDistance
                    // Perspective compensation: rotate to face the camera eye at the origin
                    eulerRotation.y: -Math.atan2(x, sceneCamera.stickDistance) * 180 / Math.PI
                    eulerRotation.x: Math.atan2(y, sceneCamera.stickDistance) * 180 / Math.PI
                    ThumbStick {
                        axes: leftStickControl.axes
                    }
                }
            }

            DirectionalLight {
                id: directionalLight
                eulerRotation: Qt.vector3d(-30, 30, 0)
            }
        }

        OrbitCameraController {
            origin: cameraNode
            camera: sceneCamera
        }

        Node {
            id: cameraViewScreen
            eulerRotation: Qt.vector3d(180, 0, 180)
            x: dogsEyeView.width / 2         // center on axis
            y: dogsEyeView.height / 2 + 100  // center on line of sight
            z: 1000                          // in front of the dog; TODO calibrate?
            Image {
                id: dogsEyeView
                width: 1920
                height: 1080
                cache: false
                source: "image://camera/" + ReceivedImageProvider.currentFrame

                Text {
                    anchors {
                        horizontalCenter: parent.horizontalCenter
                        bottom: parent.bottom
                        margins: 6
                    }
                    color: "white"
                    text: cameraNode.eulerRotation.x.toFixed(2) + ", " +
                          cameraNode.eulerRotation.y.toFixed(2) + ", " +
                          cameraNode.eulerRotation.z.toFixed(2)
                }
            }
        }

        Node {
            id: lidarRepresentation
            y: 100
            Model {
                scale: Qt.vector3d(0.1, 0.1, 0.01)
                source: "#Cube"
                instancing: LidarInstanceTable {
                    ranges: laserSub.ranges
                    intensities: laserSub.intensities
                    angleIncrement: laserSub.angleIncrement
                }
                materials: [
                    PrincipledMaterial {
                        alphaMode: PrincipledMaterial.Opaque
                        cullMode: PrincipledMaterial.NoCulling
                        emissiveFactor: Qt.vector3d(0.1, 0.1, 0.1)
                    }
                ]
            }
        }

        Dogzilla {
            id: robotRoot
            control: DogzillaControl {
                id: ctl
            }
        }
        AxisHelper {
            y: -115
            scale: Qt.vector3d(0.2, 0.2, 0.2)
        }
    }

    Ros2.Node {
        id: rosNode
        nodeName: "dogzilla"

        SensorMsgs.BatteryStateSubscriber {
            id: batterySub
            topic: `/${rosNode.nodeName}/battery_state`
        }

        SensorMsgs.JointStateSubscriber {
            id: jointStateSubscriber
            topic: `/${rosNode.nodeName}/joint_states`
            qos.queueSize: 1
            qos.reliability: SensorMsgs.JointStateSubscriber.ReliabilityBestEffort
            qos.history: SensorMsgs.JointStateSubscriber.HistoryKeepLast

            onMessageReceived: function (msg) {
                // console.log("JointStateSubscriber got", msg.name, msg.position, JSON.stringify(msg))
                robotRoot.control.updateJointState(msg.name, msg.position);
            }
        }

        SensorMsgs.CompressedImageSubscriber {
            id: imageSubscriber
            topic: `/${rosNode.nodeName}/camera/image/compressed`
            onMessageReceived: function(msg) {
                console.log(JSON.stringify(msg))
                // const QImage &im, int frame, int sec, int nsec
                ReceivedImageProvider.setImage(msg.image, msg.header.frameId,
                                               msg.header.stamp.sec, msg.header.stamp.nanosec)
            }
        }

        SensorMsgs.LaserScanSubscriber {
            id: laserSub
            topic: `/${rosNode.nodeName}/sensor_msgs/msg/LaserScan`
        }

        // step sideways
        property real strafeSpeed: rightStickControl.axes.x * -50
        // look up/down: change lidar and camera angle
        // must be < 90 to avoid gimbal lock (which would cause other angles to become non-zero)
        // anyway the robot supports a much narrower range than that
        property real pitch: rightStickControl.axes.y * 80
        // yaw by stepping
        property real turnSpeed: leftStickControl.axes.x * -100
        // walk forwards or backwards
        property real walkSpeed: leftStickControl.axes.y * 100

        GeomMsgs.TwistPublisher {
            id: cmdVel
            topic: `/${rosNode.nodeName}/cmd_vel` // legacy ROS1-style command topic, still in use
            linear: Qt.vector3d(rosNode.walkSpeed, rosNode.strafeSpeed, 0)
            angular: Qt.vector3d(0, 0, rosNode.turnSpeed)
        }

        GeomMsgs.PosePublisher {
            topic: `/${rosNode.nodeName}/body_pose/command` // modern style for command/state topic separation
            orientation: GeomMsgs.Quaternion.fromEulerAngles(0, rosNode.pitch, 0)
        }
    }

    ControlPanel {
        id: panel
        anchors.right: parent.right
        anchors.top: parent.top
        anchors.bottom: parent.bottom
        anchors.margins: 12
        width: Math.min(420, Math.max(280, parent.width * 0.28))
        targetRobot: robotRoot
        batteryLevel: batterySub.percentage
    }

    ThumbStickControl {
        id: rightStickControl
        width: parent.width / 7
        anchors {
            bottom: parent.bottom
            right: parent.right
        }
        Text {
            anchors {
                right: parent.right
                bottom: parent.bottom
                margins: 6
            }
            color: "white"
            text: `${rightStickControl.axes.x.toFixed(2)} ${rightStickControl.axes.y.toFixed(2)}` +
                  ` strafe ${rosNode.strafeSpeed.toFixed(2)} pitch ${rosNode.pitch.toFixed(2)}`
        }
    }

    ThumbStickControl {
        id: leftStickControl
        width: parent.width / 6
        anchors {
            bottom: parent.bottom
            left: parent.left
        }
        Text {
            anchors {
                left: parent.left
                bottom: parent.bottom
                margins: 6
            }
            color: "white"
            text: `${leftStickControl.axes.x.toFixed(2)} ${leftStickControl.axes.y.toFixed(2)}` +
                  ` turn ${rosNode.turnSpeed.toFixed(2)} walk ${rosNode.walkSpeed.toFixed(2)}`
        }
    }
}
